### PR TITLE
Fixing bug with inline email verification. closes #74

### LINKED ISSUE #74: Fix register with email
Add inline email validation against the server for existing users

### PR DESCRIPTION
**Pull request by ethanelliott**

### CODE REVIEW

File: server/src/api/Controllers/UserController.ts [hunk 1]
```diff
@@ -66,13 +66,20 @@ export class UserController {
...
         @BodyParam('username', {required: true}) username: string
     ): Promise<any> {
         return {exists: this.userService.getAllUsers().filter(e => e.username === username).length > 0}
     }
 
+    @Post('/exists/email')
+    public async doesEmailExist(
+        @BodyParam('email', {required: true}) email: string
+    ): Promise<any> {
+        return {exists: this.userService.getAllUsers().filter(e => e.email === email).length > 0}
```
Comment (anirudhmungre) [inline server/src/api/Controllers/UserController.ts]: Wouldn't it be faster to query the db for the specified email and then check if any rows are returned?

File: front/src/views/Register.vue [hunk 2]
```diff
@@ -248,11 +255,34 @@
...
+                            this.emailLoading = false;
+                            this.emailError = 'Something went wrong!';
+                        })
+                    } else {
+                        this.emailLoading = false;
+                        this.emailError = 'Invalid Email';
+                    }
+                } else {
+                    this.emailLoading = false;
+                    this.emailValid = false;
```
Comment (anirudhmungre) [inline front/src/views/Register.vue]: `this.emailValid = false` is redundant because at this point it will already always be false

File: front/src/views/Register.vue [hunk 3]
```diff
@@ -248,11 +255,34 @@
...
+                    this.emailError = 'Email is required';
+                }
```
Comment (anirudhmungre) [inline front/src/views/Register.vue]:
```suggestion
                    this.emailLoading = false;
                }
```
Put this at the end and remove all `this.emailLoading = false` from every statement.

File: server/src/api/Controllers/UserController.ts (hunk 1 above)
Comment (anirudhmungre) [reply server/src/api/Controllers/UserController.ts]: im not 100% sure

File: front/src/views/Register.vue (hunk 2 above)
Comment (ethanelliott) [reply front/src/views/Register.vue]: If the user has typed an email, and then clears the text field before the function debounces it will need to stop the user from moving forward

File: front/src/views/Register.vue (hunk 3 above)
Comment (ethanelliott) [reply front/src/views/Register.vue]: this has a request through axios which is async so this wouldn't accurately show the loading
